BaseURL = "http://localhost:1313/"#"https://www.mendrugory.com/"
relativeURLs = true
languageCode = "en-us"
title = "mendrugory.com"
disqusShortname = "@mendrugory "
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."
	

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Blog"
  weight = 20
  identifier = "post"
  url = "/post/"

# Add your own params here
[params]
  author = "Gonzalo"
  avatar = "/img/avatar.jpg"
  seotitle = "Mendrugory's Web"
  subtitle = "~ A place to share ~"
  description = "Mendrugory's blog."
  paginate = 10

  # Choose your social networks
  email = "iam@mendrugory.com"
  github = "mendrugory"
  twitter = "mendrugory"
  linkedin = "gonzalogabrieljimenezfuentes"
  # weibo = "weibo_username"
  # wechat= "/img/qrcode.jpg" # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"